### PR TITLE
Devise rspec

### PR DESCRIPTION
**Pull request by TravisSperry**
Includes change in #56 
- Addition of Devise configs for Rspec
- Updated user specs (valid factory; invalid if first_name or last_name are nil)

### CODE REVIEW

**Comment by TravisSperry** [comment]
Good to merge?

**Comment by erinmadisonanthony** [comment]
Hi @TravisSperry in spec/models/user_spec.rb, did you intend to use first_name and last_name in your tests instead of username for all of them? It looks like you're running the exact same test 3 times.

**Comment by TravisSperry** [comment]
Thanks! Updated.

**Comment by jaybobo** [comment]
LGTM. 👍 

I'm going to add a new beginner issue to test `.find_for_database_authentication` with it being a public method that might be something we should do here. 

I think it'd be good for those new to factories, rspec stubs/expectations & unit testing in general.

**Pull request merged**
